name: dengue-forecasting
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.0
  - numpy=1.24.3  # Compatible with Prophet
  - pandas=2.2.3
  - matplotlib=3.10.1
  - scikit-learn=1.6.1
  - streamlit=1.45.0
  - plotly=6.0.1
  - seaborn=0.13.2
  - scipy=1.14.1
  - statsmodels=0.14.4
  - jupyter=1.1.1
  - ipywidgets=7.7.2
  - openpyxl=3.1.5
  - nbformat=5.10.4
  - pip=25.1.1
  - pip:
    - prophet==1.1.5
    - cmdstanpy==1.2.4